homework_1
UteshevaEM/Papka pull request #2
Opened 2019-11-24 19:53 UTC by UteshevaEM

2019-12-19 20:46 UTC, illarionovEA requested changes
неверный формат файла

2019-12-20 11:18 UTC, UteshevaEM commented
А за это тоже надо апнуться на кодворс?

2019-12-20 11:25 UTC, illarionovEA commented
да

2019-12-20 11:28 UTC, UteshevaEM commented
https://www.codewars.com/users/UteshevaEM
вот профиль, я уже дважды апнулась и теперь на 6
вот сейчас хочу использовать первый из них, второй потом напишу, где

2019-12-20 13:43 UTC, illarionovEA approved these changes

2019-12-20 22:50 UTC, merged