Create hmwrk2.ipynb
UteshevaEM/Papka pull request #3
Opened 2019-12-07 14:41 UTC by UteshevaEM

Без алгоритма k-means, его отправлю позже

почему-то не работает ссылка на dataset :(

2019-12-08 11:54 UTC, illarionovEA requested changes
все ячейки должны быть запущены и выводы представлены
нужно доделать все задания

2019-12-19 20:46 UTC, illarionovEA commented
два файла на одно дз, нужно оставить только один

2019-12-20 08:37 UTC, UteshevaEM commented
удалила лишние файлы
я же надеюсь, за просто удаление не надо будет делать дополнительные задачи? :(

2019-12-20 10:29 UTC, illarionovEA approved these changes

2019-12-20 10:57 UTC, merged